name: Generate Snake

on:
  schedule:
    - cron: "0 */12 * * *" # every 12 hours
  workflow_dispatch:       # allow manual trigger

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Generate github-user-contribution.svg
        uses: Platane/snk@v3
        with:
          github_user_name: AK-I-RA
          outputs: dist/github-user-contribution.svg

      - name: Push to output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
